# You must first rake db:{create,migrate}, then log in to the app via LinkedIn to create a User. The jobs are asscoiated with a specifc user, so they need a user to attach to.

Status.destroy_all
Job.destroy_all
Contact.destroy_all

Status.create([{name: "interested"}, {name: "applied"}, {name: "interviewed"}, {name: "offer"}, {name: "accepted"}])

statuses = Status.all
salary = [75000, 78000, 80000, 82000, 83000, 87000, 90000, 92000, 95000, 97000, 103000]
user = User.first
user.jobs.create!(company: "Workiva Inc.", title: "Software Engineer", description: "Write cutting edge code. Work on any part of the stack - from very rich, highly complex H5 applications to hugely scalable distributed systems. Deploy quickly to production. Work on an agile development team. Work with other engineers, designers, and test engineers to bring prototypes to life. What Youll Need: BS CS/EE/CE, or equivalent job experience. A passion for coding and building complex web applications. A passion and excitement for mentoring and developing junior engineers. Proficient in numerous front end and back end languages; expertise as a full stack engineer. Fluent with the latest web technologies (Python, Java, Go, Docker, NoSQL). Experience with AWS or Google Cloud Platform (GCP) technologies. Excellent problem-solving skills, great attention to details. Strong communication skills, both verbal and written. Ability to learn new technologies quickly and understand a wide variety of technical challenges to be solved. Statistics and data analytics background, passion for data science.  Experience with Hadoop or Spark. Experience in Machine Learning in Production Environments. Familiarity writing code that works across all popular platforms and browsers. Experience with Google Compute Engine. Experience with Docker or other container systems. Experience with Graph Databases", city: "Denver", state: "CO", salary: salary.sample, post_url: "https://www.workiva.com/", status: statuses.sample)

user.jobs.create!(company: "Computronix", title: "Software Engineer", description: "Ability to develop, code, test, and debug customized software for specific applications using PL/SQL, SQL, Python, C#, relational databases, HTML, and JavaScript or a combination. Experience in developing applications in conjunction with Oracle databases and familiarity with relational database concepts. Prefer database management experience (Oracle 10g and up), with respect to tuning, performance, monitoring, implementation capacity planning, space management and reorganization, backup and recovery, and quality assurance. Ability to develop solutions from detailed business and technical specifications. A desire for continuous and ongoing growth and development. Willingness to work in a team environment. A commitment to be respectful of peers, team members and clients; willingness to trust others and be trustworthy, and a keen desire to serve coworkers and clients. Good verbal and written communication skills. Required Education and Experience: Bachelors degree, preferably in Computer Science or Information Technology or equivalent experience and training. In lieu of education, must have 1 to 2 years software programming experience, preferably with some experience in a software consulting company. Candidates must be willing to work in our Denver area (Lakewood) office", city: "Greenwood Village", state: "CO", salary: salary.sample, post_url: "www.computronix.com", status: statuses.sample)

user.jobs.create!(company: "Bytion", title: "Senior Software Engineer", description: "Work on large-scale, custom distributed software systems using the MEAN Stack. Lead teams of software engineers. Be responsible for the quality of software and resolving issues. Be a mentor and role model to less experienced developers. Employ Agile development including task estimation, test automation, deployment automation and Continuous Integration to improve overall execution speed and product quality. Work within an Agile Environment, including SCRUM and/or XP (Extreme Programming). Develop and review architecture plans. Coordinate with others across the organization to build fully integrated systems. Troubleshoot and resolve varying levels of technical issues. Add value by being current with new trends and frameworks within the developer community. Drive adoption of modern development strategies, processes, and methods. Set and maintain priorities in a multi-project environment.", city: "Denver", state: "CO", salary: salary.sample, post_url: "http://bytion.io/", status: statuses.sample)

user.jobs.create!(company: "Journal Technologies", title: "Software Developer", description: "Design, develop, troubleshoot, debug and test custom software solutions. Maintain and improve the performance of existing software solutions. Provide feedback to business analysts based on interface requirements. Test and maintain software products to ensure strong functionality and optimization. Recommend improvements to existing software programs as necessary. Some client-facing activity
Light Travel", city: "Denver", state: "CO", salary: salary.sample, post_url: "http://journaltech.com/", status: statuses.sample)

user.jobs.create!(company: "United Launch Alliance", title: "Software Engineer", description: "A technical Bachelor of Science degree with software emphasis or Computer Science degree. 4 - 8 years of related work experience. Experience as part of a multi-developer team utilizing software lifecycle processes (including but not limited to: requirements analysis, requirements documentation, object oriented design, design documentation, code implementation, unit testing, integration testing, and authoring and execution of formal test procedures). Experience with C++ software development in a Linux/Unix environment. Experience with object oriented design and complex C++ software. systems utilizing interprocess communication, shared memory, semaphores, and class libraries. Linux/Unix experience with debuggers, source code control, makefiles, shell scripts, pipes, redirection, and real-time systems.", city: "Denver", state: "CO", salary: salary.sample, post_url: "http://www.ulalaunch.com/", status: statuses.sample)


Job.all.each do |job|
  job.contacts.create(name: Faker::Name.name, phone: Faker::PhoneNumber.cell_phone, email: Faker::Internet.email, image_url: "http://lorempixel.com/200/200")
end
